### PR TITLE
Update cards-manifest.json

### PR DESCRIPTION
**Pull request by QustomQure**
Updated many Artist names. Stopped for today

### CODE REVIEW

**Comment by 0ttah** [comment]
Thanks for the added info. I need to rebase your changes since you're out of sync but don't worry I'll sort it out.

**Comment by QustomQure** [comment]
Nice to hear. I will proceed yesterday. 1:39 Am atm :)

**Comment by 0ttah** [comment]
If you could rebase and merge then it will be good to go.

https://help.github.com/articles/syncing-a-fork/

**Comment by 0ttah** [comment]
All fixed! Make sure you pull the changes. Thanks for the pull request I'm merging it into the master branch now.

**Comment by 0ttah** [comment]
> this commit must be deleted
Why?

**Pull request merged**
